name: Backend Pipeline

on:
  push:
    branches:
      - '**'
    paths:
      - 'backend/**'
      - 'tools/*-backend'
      - '.github/workflows/backend*'
  pull_request:
    branches:
      - '**'
    paths:
      - 'backend/**'
      - 'tools/*-backend'
      - '.github/workflows/backend*'
  workflow_dispatch:


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      - name: Backend build
        run: ./tools/build-backend

  db-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install backend dependencies
        run: ./tools/build-backend

      - name: Run Integration Tests
        run: ./tools/test-backend


  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main')
    needs: db-tests
    steps:
      - uses: actions/checkout@v4
      - name: Deploy PROD
        if: github.ref == 'refs/heads/main'
        env:
          RENDER_BACKEND_HOOK: ${{ secrets.RENDER_BACKEND_HOOK }}
        run: bash tools/deploy-to-render RENDER_BACKEND_HOOK