name: Run init.sql on production database

on:
  workflow_dispatch:

jobs:
  run-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Set environment variables
        run: |
          echo "REAL_PG_HOST=${{ secrets.POSTGRES_HOST }}" >> $GITHUB_ENV
          echo "REAL_PG_DB=${{ secrets.POSTGRES_DB }}" >> $GITHUB_ENV
          echo "REAL_PG_USER=${{ secrets.POSTGRES_USER }}" >> $GITHUB_ENV
          echo "REAL_PG_PASS=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_ENV

      - name: Make script executable
        run: chmod +x run-init.sh

      - name: Run init script
        run: ./run-init.sh
